spring.application.name=ai-study-assistant
spring.datasource.url=jdbc:postgresql://localhost:5432/aiassistant
spring.datasource.username=abd_mjahdi
spring.datasource.password=mp7ak47p90

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always